apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: stateflow
spec:
  type: LoadBalancer
  selector:
    app: stateflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80