apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: stateflow
data:
  consumer: |
    {
      "bootstrap_servers": ""
    }
  producer: |
    {
      "bootstrap_servers": ""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateflow-frontend
  namespace: stateflow
spec:
  replicas: 20
  selector:
    matchLabels:
      app: stateflow-frontend
  template:
    metadata:
      labels:
        app: stateflow-frontend
    spec:
      containers:
        - name: fastapi-frontend
          image: "wzorgdrager/stateflow-frontend-pyflink:0.0.3"
          env:
          - name: "PYFLINK"
            value: "1"
          - name: "TIMEOUT"
            value: "20"
          - name: "CONSUMER_CONF"
            value:  "/tmp/consumer-config.json"
          - name: "PRODUCER_CONF"
            value: "/tmp/producer-config.json"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /tmp
              readOnly: false
          resources:
            requests:
              memory: "1024Mi"
              cpu: "750m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-config
            items:
              - key: consumer
                path: consumer-config.json
              - key: producer
                path: producer-config.json
