apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  namespace: stateflow
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: apache/flink-statefun:3.0.0
          env:
          - name: ROLE
            value: "worker"
          - name: MASTER_HOST
            value: "jobmanager"
          resources:
            requests:
              memory: "8000Mi"
              cpu: "1750m"
            limits:
              memory: "8192Mi"
              cpu: "2000m"
          ports:
            - containerPort: 6122
              name: rpc
          livenessProbe:
            tcpSocket:
              port: 6122
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf/
            - name: statefun-config-volume
              mountPath: /opt/statefun/modules/stateflow/
          securityContext:
            runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j.properties
                path: log4j-console.properties
        - name: statefun-config-volume
          # Create configMap using kubectl: kubectl create configmap module --from-file=module_key=module.yaml
          configMap:
            name: statefun-config
            items:
              - key: statefun-module
                path: module.yaml