apiVersion: v1
kind: Service
metadata:
  name: statefun-loadbalancer
  namespace: stateflow
spec:
  type: LoadBalancer
  selector:
    app: stateflow-remote-statefun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80